import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? ''

export const metadata: Metadata = {
  title: 'Privacy Policy — GramSathi',
  description: 'Privacy Policy for GramSathi — Your Rural AI Assistant',
  alternates: {
    canonical: `${APP_URL}/legal/privacy-policy`,
  },
}

const SECTIONS = [
  {
    title: 'Information We Collect',
    body: [
      'Mobile phone number — used as your unique identifier to create and manage your account.',
      'Name (optional) — if you choose to provide it during registration.',
      'Language preference — so we can respond in your language.',
      'Pincode — to show nearby shops and health facilities in your area.',
      'Health queries and conversation history — the text or voice messages you send to the Health Assistant, stored to provide multi-turn conversation context.',
      'Voice recordings — temporarily processed to convert speech to text. Audio files are stored on secure AWS S3 storage.',
    ],
  },
  {
    title: 'How We Use Your Information',
    body: [
      'To provide personalised health guidance, nearby clinic/pharmacy discovery, and local commerce features.',
      'To remember your language and location preferences across sessions.',
      'To improve the quality and accuracy of AI responses over time.',
      'To allow shop owners to fulfil orders placed through the app.',
    ],
  },
  {
    title: 'Data Storage & Security',
    body: [
      'Your data is stored on secure AWS infrastructure (DynamoDB, S3) in the ap-south-1 (Mumbai) region.',
      'All communication between your device and our servers is encrypted using HTTPS/TLS.',
      'Authentication tokens (JWT) are short-lived and stored only in your browser\'s local storage.',
      'Voice recordings are processed and then retained in encrypted S3 storage. They are not shared with any third party.',
    ],
  },
  {
    title: 'AI & Third-Party Services',
    body: [
      'Health advice is generated by Amazon Bedrock (Claude model). Your query text is sent to this service to produce a response.',
      'Voice transcription is handled by Amazon Transcribe.',
      'Text-to-speech audio is generated by Amazon Polly.',
      'Nearby clinic and shop discovery may use Google Places API; only your search query and approximate location are shared.',
      'None of your personal details (phone number, name) are shared with these AI/ML services.',
    ],
  },
  {
    title: 'Health Information Disclaimer',
    body: [
      'GramSathi provides general health information only and is not a substitute for professional medical advice, diagnosis, or treatment.',
      'Always consult a qualified doctor for medical concerns.',
      'In case of a medical emergency, call 108 immediately.',
    ],
  },
  {
    title: 'Data Retention',
    body: [
      'Your account and conversation history are retained as long as your account is active.',
      'You can sign out at any time; your local session data is cleared from your device.',
      'To request permanent deletion of your data, contact us at the address below.',
    ],
  },
  {
    title: 'Children\'s Privacy',
    body: [
      'GramSathi is not intended for use by children under the age of 13. We do not knowingly collect personal information from children.',
    ],
  },
  {
    title: 'Changes to This Policy',
    body: [
      'We may update this Privacy Policy from time to time. The "Last updated" date at the top of this page will reflect any changes.',
      'Continued use of the app after changes are posted constitutes your acceptance of the revised policy.',
    ],
  },
  {
    title: 'Contact Us',
    body: [
      'If you have questions about this Privacy Policy or wish to exercise your data rights, please contact us at:',
      'Email: privacy@gramsathi.in',
    ],
  },
]

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-dvh bg-background">
      {/* Header */}
      <div className="sticky top-0 z-10 flex items-center gap-3 bg-surface px-4 py-4 shadow-sm md:px-8">
        <Link
          href="/"
          className="flex items-center gap-1 rounded-full p-1.5 text-textSecondary hover:bg-surface-variant hover:text-primary transition"
        >
          <ArrowLeft className="h-5 w-5" />
        </Link>
        <div>
          <p className="font-bold text-textPrimary leading-tight">Privacy Policy</p>
          <p className="text-xs text-textSecondary">GramSathi</p>
        </div>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-3xl px-5 py-8 md:px-8 md:py-12">
        {/* Intro */}
        <div className="mb-8 rounded-2xl bg-primary/5 border border-primary/15 px-5 py-4">
          <p className="text-sm text-textSecondary leading-relaxed">
            <span className="font-semibold text-textPrimary">Last updated: March 2026</span>
            <br />
            GramSathi (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;the app&rdquo;) is committed to protecting your privacy.
            This policy explains what data we collect, how we use it, and the choices you have.
            By using GramSathi you agree to the practices described here.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-7">
          {SECTIONS.map((section, i) => (
            <section key={i}>
              <h2 className="mb-3 text-base font-bold text-textPrimary">
                {i + 1}. {section.title}
              </h2>
              <ul className="space-y-2">
                {section.body.map((point, j) => (
                  <li key={j} className="flex gap-2.5 text-sm text-textSecondary leading-relaxed">
                    <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-primary/50" />
                    {point}
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-10 border-t border-divider pt-6 text-center text-xs text-textHint">
          <p>© {new Date().getFullYear()} GramSathi. All rights reserved.</p>
          <p className="mt-1">
            <Link href="/" className="text-primary hover:underline">
              Back to GramSathi
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
